"""nullability on Post title and body

Revision ID: c8570dd103f4
Revises: 547706847025
Create Date: 2022-05-12 17:22:48.367457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8570dd103f4'
down_revision = '547706847025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('posts', 'body',
               existing_type=sa.VARCHAR(length=4000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body',
               existing_type=sa.VARCHAR(length=4000),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###
